<nav class="bg-white border-b border-gray-100"><div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div class="flex justify-between h-16"><div class="flex"><div class="flex-shrink-0 flex items-center"><a href="{{route('dashboard')}}"><img src="/img/logo.png" style="max-height: 50px; border: 1px solid rgb(188, 145, 67) !important; border-radius: 50%; padding: 7px; box-shadow: rgba(0, 0, 0, 0.1) 0px 20px 25px -5px, rgba(0, 0, 0, 0.04) 0px 10px 10px -5px;"></a></div> <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex"><a href="{{route('dashboard')}}" class="inline-flex items-center px-1 pt-1 border-b-2 border-indigo-400 text-sm font-medium leading-5 text-gray-900 focus:outline-none focus:border-indigo-700 transition duration-150 ease-in-out normalalized-table-text">
                            Dashboard
                        </a></div></div> <div class="hidden sm:flex sm:items-center sm:ml-6"><div class="ml-3 relative"><div class="relative"><div><button class="flex items-center text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300 transition duration-150 ease-in-out"><div></div> <div class="ml-1"></div></button></div> <div class="fixed inset-0 z-40" style="display: none;"></div> <div class="absolute z-50 mt-2 rounded-md shadow-lg w-48 origin-top-right right-0" style="display: none;"><div class="rounded-md shadow-xs py-1 bg-white"><div class="block px-4 py-2 text-xs text-gray-400">
                                    Manage Account
                                </div> <div><a class="block px-4 py-2 text-sm leading-5 text-gray-700 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 transition duration-150 ease-in-out">
                                    Profile
                                </a></div> <!----> <div class="border-t border-gray-100"></div> <!----> <form><div><button type="submit" class="block w-full px-4 py-2 text-sm leading-5 text-gray-700 text-left hover:bg-gray-100 focus:outline-none focus:bg-gray-100 transition duration-150 ease-in-out">
                                        Logout
                                    </button></div></form></div></div></div></div></div> <div class="-mr-2 flex items-center sm:hidden"><button class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out"><svg stroke="currentColor" fill="none" viewBox="0 0 24 24" class="h-6 w-6"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" class="inline-flex"></path> <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" class="hidden"></path></svg></button></div></div></div> <div class="sm:hidden hidden"><div class="pt-2 pb-3 space-y-1"><div><a href="{{route('dashboard')}}" class="block pl-3 pr-4 py-2 border-l-4 border-indigo-400 text-base font-medium text-indigo-700 bg-indigo-50 focus:outline-none focus:text-indigo-800 focus:bg-indigo-100 focus:border-indigo-700 transition duration-150 ease-in-out">
                    Dashboard
                </a></div></div> <div class="pt-4 pb-1 border-t border-gray-200"><div class="flex items-center px-4"><div class="flex-shrink-0"><img src="https://ui-avatars.com/api/?name=Pierce+Prange&amp;color=7F9CF5&amp;background=EBF4FF" class="h-10 w-10 rounded-full"></div> <div class="ml-3"><div class="font-medium text-base text-gray-800"></div> <div class="font-medium text-sm text-gray-500">streamline.our.designs@gmail.com</div></div></div> <div class="mt-3 space-y-1"><div><a href="{{route('user/profile')" class="block pl-3 pr-4 py-2 border-l-4 border-transparent text-base font-medium text-gray-600 hover:text-gray-800 hover:bg-gray-50 hover:border-gray-300 focus:outline-none focus:text-gray-800 focus:bg-gray-50 focus:border-gray-300 transition duration-150 ease-in-out">
                        Profile
                    </a></div> <!----> <form method="POST"><div><button class="w-full text-left block pl-3 pr-4 py-2 border-l-4 border-transparent text-base font-medium text-gray-600 hover:text-gray-800 hover:bg-gray-50 hover:border-gray-300 focus:outline-none focus:text-gray-800 focus:bg-gray-50 focus:border-gray-300 transition duration-150 ease-in-out">
                            Logout
                        </button></div></form> <!----></div></div></div></nav>

                        <header class="bg-white shadow"><div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8"><span class="normalalized-table-text">Welcome</span></div></header>